#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FSM_ITC")]
	public partial class LMSMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LMSMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LMSMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LMSMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LMSMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LMS_TOPICSMASTER_LISTING> LMS_TOPICSMASTER_LISTINGs
		{
			get
			{
				return this.GetTable<LMS_TOPICSMASTER_LISTING>();
			}
		}
		
		public System.Data.Linq.Table<LMS_CATEGORYMASTERLIST> LMS_CATEGORYMASTERLISTs
		{
			get
			{
				return this.GetTable<LMS_CATEGORYMASTERLIST>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LMS_TOPICSMASTER_LISTING")]
	public partial class LMS_TOPICSMASTER_LISTING
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<int> _SEQ;
		
		private System.Nullable<long> _TOPICID;
		
		private string _TOPICNAME;
		
		private string _TOPICBASEDON;
		
		private string _TOPICSTATUS;
		
		private string _CREATEDBY;
		
		private System.Nullable<System.DateTime> _CREATEDON;
		
		public LMS_TOPICSMASTER_LISTING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="Int")]
		public System.Nullable<int> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOPICID", DbType="BigInt")]
		public System.Nullable<long> TOPICID
		{
			get
			{
				return this._TOPICID;
			}
			set
			{
				if ((this._TOPICID != value))
				{
					this._TOPICID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOPICNAME", DbType="NVarChar(300)")]
		public string TOPICNAME
		{
			get
			{
				return this._TOPICNAME;
			}
			set
			{
				if ((this._TOPICNAME != value))
				{
					this._TOPICNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOPICBASEDON", DbType="NVarChar(300)")]
		public string TOPICBASEDON
		{
			get
			{
				return this._TOPICBASEDON;
			}
			set
			{
				if ((this._TOPICBASEDON != value))
				{
					this._TOPICBASEDON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOPICSTATUS", DbType="NVarChar(10)")]
		public string TOPICSTATUS
		{
			get
			{
				return this._TOPICSTATUS;
			}
			set
			{
				if ((this._TOPICSTATUS != value))
				{
					this._TOPICSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDBY", DbType="NVarChar(50)")]
		public string CREATEDBY
		{
			get
			{
				return this._CREATEDBY;
			}
			set
			{
				if ((this._CREATEDBY != value))
				{
					this._CREATEDBY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDON", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDON
		{
			get
			{
				return this._CREATEDON;
			}
			set
			{
				if ((this._CREATEDON != value))
				{
					this._CREATEDON = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LMS_CATEGORYMASTERLIST")]
	public partial class LMS_CATEGORYMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _CATEGORYID;
		
		private string _CATEGORYNAME;
		
		private string _CATEGORYDESCRIPTION;
		
		private string _CATEGORYSTATUS;
		
		private string _CreateDate;
		
		private string _CreateUser;
		
		private string _ModifyDate;
		
		private string _ModifyUser;
		
		public LMS_CATEGORYMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORYID", DbType="Int")]
		public System.Nullable<int> CATEGORYID
		{
			get
			{
				return this._CATEGORYID;
			}
			set
			{
				if ((this._CATEGORYID != value))
				{
					this._CATEGORYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORYNAME", DbType="NVarChar(250)")]
		public string CATEGORYNAME
		{
			get
			{
				return this._CATEGORYNAME;
			}
			set
			{
				if ((this._CATEGORYNAME != value))
				{
					this._CATEGORYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORYDESCRIPTION", DbType="NVarChar(300)")]
		public string CATEGORYDESCRIPTION
		{
			get
			{
				return this._CATEGORYDESCRIPTION;
			}
			set
			{
				if ((this._CATEGORYDESCRIPTION != value))
				{
					this._CATEGORYDESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORYSTATUS", DbType="NVarChar(50)")]
		public string CATEGORYSTATUS
		{
			get
			{
				return this._CATEGORYSTATUS;
			}
			set
			{
				if ((this._CATEGORYSTATUS != value))
				{
					this._CATEGORYSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
		public string CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="NVarChar(50)")]
		public string ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
